import { embedCustomLinks } from "../../utils/utils";

export const websitesDb = [
  {
    projectName: "The Portfolio",
    projectId: "e2f9658b-f9bb-4d2c-ac8c-113a56d9204f",
    projectTagLine: "A Thoughtfully Curated Portfolio of Elegant Creations",
    link: "https://hammadtayyab.vercel.app/",
    imageLink: "/images/websites/my_portfolio.png",
    info: "This portfolio project showcases a minimalist design, highlighting my work and skills with clarity and finesse. The aim was to provide a seamless user experience and intuitive navigation, creating a comprehensive and sophisticated display of my professional journey.",
    roles: [
      "Data Analyst",
      "Designer",
      "Developer",
      "Maintainer",
      "Product Manager",
      "Tester/Quality Assurance",
      "Researcher",
      "DevOps Engineer",
      "Technical Writer",
      "Project Manager",
    ],
    techStack: [
      "NextJs",
      "React",
      "TypeScript",
      "TailwindCSS",
      "HTML",
      "CSS",
      "JavaScript",
      "Git",
      "Vercel",
    ],
  },
  {
    projectName: "The Portfolio V1",
    projectId: "e2f9658b-f9bb-4d2c-ac8c-1345a56d9204f",
    projectTagLine: "The Legacy: Honoring My Journey with Enduring Style.",
    link: "https://hammadtayyab-v1.vercel.app/",
    imageLink: "/images/websites/the_portfolio_v1.png",
    info: "This is the first version of my portfolio project, featuring a clean and simple design that showcases my work and skills. The focus was on creating a user-friendly experience with easy navigation, allowing visitors to explore my professional journey with ease.",
    roles: [
      "Data Analyst",
      "Designer",
      "Developer",
      "Maintainer",
      "Product Manager",
      "Tester/Quality Assurance",
      "Researcher",
      "DevOps Engineer",
      "Technical Writer",
      "Project Manager",
    ],
    techStack: [
      "NextJs",
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "Git",
      "Vercel",
    ],
  },
  {
    projectId: "566ec8d6-4d5d-4f22-9580-2c574f7122fb",
    projectName: "Mess Menu",
    projectTagLine: "Simplifying Hostel Dining with a Digital Menu System",
    link: "https://messmenu.vercel.app/",
    imageLink: "/images/websites/mess_menu.png",
    info: "This project streamlines the process of hostel dining by offering a digital menu system for students. Monthly menus are curated through community voting, allowing students to have a say in their dining options. Originating from a friend's final year project, the focus was on user-centric design and functionality, ensuring a seamless experience for all users.",
    roles: [
      "Data Analyst",
      "Designer",
      "Developer",
      "Maintainer",
      "Product Manager",
      "Tester/Quality Assurance",
      "Researcher",
      "DevOps Engineer",
      "Technical Writer",
      "Project Manager",
    ],
    techStack: [
      "NextJs",
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "Git",
      "Vercel",
      "Firebase",
      "Firebase Auth",
    ],
  },
  {
    projectId: "e3a52953-0a4d-43c3-b874-bd55925f6a7e",
    projectName: "Islamic Dev Repo",
    projectTagLine: "A Repository of Authentic Islamic Data for Developers",
    link: "https://islamic-dev-repo.vercel.app/",
    imageLink: "/images/websites/islamic_dev_repo.png",
    info: "This project offers developers a curated repository of reliable Islamic data that can be seamlessly integrated into various applications. With a focus on authenticity and compatibility across multiple devices, this repository provides a trustworthy source of information for developers working on Islamic-related projects.",
    roles: [
      "Data Analyst",
      "Designer",
      "Developer",
      "Maintainer",
      "Product Manager",
      "Tester/Quality Assurance",
      "Researcher",
      "DevOps Engineer",
      "Technical Writer",
      "Project Manager",
    ],
    techStack: [
      "NextJs",
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "Git",
      "Vercel",
      "Python",
    ],
  },
  {
    projectId: "87693335-b9d6-434c-8428-5d8266482050",
    projectName: "Stratex",
    projectTagLine:
      "A Platform for Streaming the Best Madina Arabic Course Online",
    link: "https://arabiccourses.vercel.app/",
    imageLink: "/images/websites/arabic_courses.png",
    info: `The goal of this project was to establish an online platform for the popular Madina Arabic course, allowing users to stream videos from the cloud and track their progress. Initially, the videos were only available for download, but this platform offers a more convenient streaming experience. You can learn more about the course at ${embedCustomLinks(
      {
        link: "https://abdurrahman.org/arabic-learning/dvds/",
        title: "AbdurRahman.Org",
      }
    )}. Arabic Courses enhances accessibility and convenience for users, making the learning process smoother and more enjoyable.`,
    roles: [
      "Data Analyst",
      "Designer",
      "Developer",
      "Maintainer",
      "Product Manager",
      "Tester/Quality Assurance",
      "Researcher",
      "DevOps Engineer",
      "Technical Writer",
      "Project Manager",
    ],
    techStack: [
      "NextJs",
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "Git",
      "Vercel",
      "Firebase",
      "Firebase Auth",
    ],
  },
  {
    projectId: "87693335-b9d6-434c-8428-5d8266482050",
    projectName: "Arabic Courses",
    projectTagLine:
      "A Platform for Streaming the Best Madina Arabic Course Online",
    link: "https://arabiccourses.vercel.app/",
    imageLink: "/images/websites/arabic_courses.png",
    info: `The goal of this project was to establish an online platform for the popular Madina Arabic course, allowing users to stream videos from the cloud and track their progress. Initially, the videos were only available for download, but this platform offers a more convenient streaming experience. You can learn more about the course at ${embedCustomLinks(
      {
        link: "https://abdurrahman.org/arabic-learning/dvds/",
        title: "AbdurRahman.Org",
      }
    )}. Arabic Courses enhances accessibility and convenience for users, making the learning process smoother and more enjoyable.`,
    roles: [
      "Data Analyst",
      "Designer",
      "Developer",
      "Maintainer",
      "Product Manager",
      "Tester/Quality Assurance",
      "Researcher",
      "DevOps Engineer",
      "Technical Writer",
      "Project Manager",
    ],
    techStack: [
      "NextJs",
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "Git",
      "Vercel",
      "Firebase",
      "Firebase Auth",
    ],
  },
];
