import NavBar from "../components/Nav_bar/nav_bar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DevicePreview from "../components/Device_preview/device_preview";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {
          <div>
            <NavBar></NavBar>
            {/* main content */}
            {children}

            {/* sticks on the screen */}
            {/* <DevicePreview> </DevicePreview> */}
          </div>
        }
      </body>
    </html>
  );
}
