import NavBar from "@/Components/Nav_bar/nav_bar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DevicePreview from "@/Components/Device_preview/device_preview";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {
          <div>
            <NavBar>{children}</NavBar>
            <div>
              <DevicePreview> </DevicePreview>
            </div>
          </div>
        }
      </body>
    </html>
  );
}
